version: "3.9"

services:
  datanode-1:
    container_name: datanode-1
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    ports:
      - 9864:9864
    environment:
      SERVICE_PRECONDITION: "10.123.252.194:9870"
    env_file:
      - ./hadoop.env

  spark-worker-1:
    container_name: spark-worker-1
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    ports:
      - 8081:8081
    environment:
      - "SPARK_MASTER=10.123.252.207:7077"

  zookeeper-1:
    container_name: zookeeper-1
    image: confluentinc/cp-zookeeper:7.2.1
    network_mode: host
    restart: unless-stopped
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: 10.123.252.231:2888:3888;10.123.252.194:2888:3888;10.123.252.207:2888:3888
  
  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - 19092:19092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 10.123.252.231:2181,10.123.252.194:2181,10.123.252.207:2181
      KAFKA_PARTITION_ASSIGNMENT_STRATEGY: org.apache.kafka.clients.consumer.RoundRobinAssignor
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://10.123.252.231:9092,EXTERNAL://host.docker.internal:19092"
    restart: unless-stopped
    depends_on:
      - zookeeper-1

  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    restart: always
    depends_on:
      - zookeeper-1
      - kafka-1
    ports:
      - "8082:8082"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "10.123.252.231:9092,10.123.252.194:9092,10.123.252.207:9092"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8082"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,OPTIONS'

  kafka-connect:
    container_name: kafka-connect
    image: confluentinc/cp-kafka-connect-base:7.2.2
    depends_on:
      - kafka-1
      - schema-registry
    ports:
      - "35000:35000"
      - "8083:8083"
    command:
    - bash
    - -c
    - |
      confluent-hub install --no-prompt confluentinc/kafka-connect-hdfs3:1.1.21
      /etc/confluent/docker/run
    environment:
      KAFKA_JMX_PORT: 35000
      KAFKA_JMX_HOSTNAME: kafka-connect
      CONNECT_BOOTSTRAP_SERVERS: "10.123.252.231:9092,10.123.252.194:9092,10.123.252.207:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-cluster-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_ZOOKEEPER_CONNECT: "zk-1:12181"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_CONNECTIONS_MAX_IDLE_MS: 180000
      CONNECT_METADATA_MAX_AGE_MS: 180000
      CONNECT_AUTO_CREATE_TOPICS_ENABLE: "true"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://10.123.252.231:8082
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://10.123.252.231:8082

  kowl:
    container_name: kowl
    image: quay.io/cloudhut/kowl:master 
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - zookeeper-1
      - kafka-1
    environment:
      # kafka-1: 10.123.252.231; kafka-2: 10.123.252.194; kafka-3: 10.123.252.207; 
      KAFKA_BROKERS: 10.123.252.231:9092,10.123.252.194:9092,10.123.252.207:9092
      CONNECT_ENABLED: true
      CONNECT_CLUSTERS_NAME: HDFS Connector
      CONNECT_CLUSTERS_URL: http://10.123.252.231:8083
      KAFKA_SCHEMAREGISTRY_ENABLED: true
      KAFKA_SCHEMAREGISTRY_URLS: http://10.123.252.231:8082

volumes:
  hadoop_datanode1:
