version: "3.9"

services:
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    ports:
      - 9864:9864
    environment:
      SERVICE_PRECONDITION: "bddst-g11-Node2.uvm.sdu.dk:9870"
    env_file:
      - ./hadoop.env

volumes:
  hadoop_datanode2:

networks:
  default:
    name: big-data-network